name: sgvrd
description: Sistema de Gestión de Votantes República Dominicana
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # HTTP & API
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.1

  # Storage
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3

  # Authentication
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Camera & Images
  image_picker: ^1.0.5
  image: ^4.1.3

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1

  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

  # UI Components
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4

  # Barcode & QR
  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_adaptive.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700